server:
  port: 8002
eureka:
  instance:
#    hostname: localhost  //this is for the local database

    #   settings for AWS RDS PostgreSQL
    hostname: mscountries.cfs6q686kbf1.us-east-2.rds.amazonaws.com
  client:
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
       defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: country-city-microservice

  datasource:
#    this is for the local datrabase

#    url: jdbc:postgresql://localhost:5432/MsCountries
#    username: admin
#    password: 12345

#   settings for AWS RDS PostgreSQL

    url: jdbc:postgresql://mscountries.cfs6q686kbf1.us-east-2.rds.amazonaws.com:5432/MsCountries
    username: postgres
    password: 12345678A

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
logging:
  level:
    org.springframework.cloud.gateway: debug
