spring:
  application:
    name: country_city-microservice

  datasource:
    url: jdbc:postgresql://localhost:5432/smartTolls_db
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
